name: nightly-run-workflow

on:
  push:
    branches:
      - master
      - release/*

  schedule:
    - cron: "0 2 * * 1-5"  # Runs at 2 AM UTC, Monday to Friday

  workflow_dispatch:
    inputs:
      text:
        description: "Enter the text you want to run"
        default: "Hello"
        required: true
        type: string

jobs:
  run-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Project into Runner
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          browsers: chrome

      - name: Print input value
        run: |
          echo "Text input value: ${{ github.event.inputs.text }}"

      - name: Run Selenium Tests
        run: |
          mvn clean test -Dsurefire.suitexmlFiles=pom.xml
