name: nightly-run-workflow
on:
  push:
    branches:
    - master
    - release/*

  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:
   inputs:
     text:
       description: 'Enter the text you want to run'
       default: 'Hello'
       required: true
       type: string
       
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - uses: actions/checkout@v1
      with :
           browsers: chrome
           
    - run: echo ${{github.event.inputs.text}}
    - run: echo 'Hello ${{inputs.text}}'

    - name: Run unit Test
      run: |
           xvfb-run --auto-servernum java -jar your-selenium-tests.jar
           mvn clean test
